language: node_js
node_js:
- node
cache: npm
os:
- osx
install:
- npm install -g gitbook-cli
- gitbook install
- gitbook build
before_script:
- npm install gulp
- npm install -g gulp-cli
script: gulp
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAJLEF6XRKWDYLCF2Q
  secret_access_key:
    secure: Tufr7LVcVOpKTS6iDrCfGOJXyqbSvZCu0169l7coeypGdFV2K8LzmfykaDSsW/khsQeo83PEYGAAlqiiBNJLxrSGs6gbz/JTjfej2PSFy7b5tbf4ZlvPmjLNhU0/kqCSf3kfu9NkeJWgvdR7Srh0uBgaBd3WeALR5jM6UxhzRL7Eu4NDwJ86POFGBmUuIvZy0qGyvj6QIkktBv64nWkk4HgFE2caIDsP8hIZs0zudJAIDSI0g9JzQLG5wsuYKcJY+gTjby697TuX4L6qKMu+TMluCzgVBMfyqryjkqlKIGv6BZGwreLaP/psQNFqm1KLYXYAaoAk8Wd5WWo3n6tWwgDmXsEDX5bTgL6dXz24xjytLUjugJRrRyvIkO5Y4Jr5HyYLlnIFfoftRpeSRQ9E6yXyx7O2HLEygPKQpxosYtNEAjgYLkS6L2jvEBhAsXaU0u6KZrETSIG8GU5m9s98QICkD9sJNg3rNU3kI092v8dsQt/QsXUpnQeeZrRl16/ZUv0WLHQkoFnnU531n4jQI9FIb/mHRwngvaSbXlwL6AlSKN9U2fRbumf2JPTo0PZAMONNb5iZvzkumYI3qPUMxRKvXxStq8pEHSwH8RS68JcQhE1e2Wf9msfVrgi8R4fd3eeP1tjnPp9+Nfr9QDu7edolufqCwMbG94J4QzxEexU=
  bucket: gitbook-testing
  local-dir: _book
  upload-dir: fme-desktop-basics
  acl: public_read
  skip_cleanup: true
